# Enable stateless CSRF protection for forms and logins/logouts
# The default conf before 7.2use classic CSRF
# Symfony 7.2 introduce CSRF TOKEN stateless to be able to have a HTML with just a string to replace dynamically by JS
# It is useful for caching page or test which compare HTML code !!

framework:
    csrf_protection:
        stateless_token_ids:
            - authenticate
            - book-item
